//! Dynamic tray item: the stopwatch mark plus a live readout of the time
//! tracked today. The mark shows whether a timer is logging: accent color
//! when running, near-white when idle.
//!
//! This is the conventional appindicator layout, the same one Slack uses
//! (its unread badge is an icon plus a native text label):
//!
//!   * `set_icon` keeps the square mark. The panel clamps square icons to
//!     the standard icon slot and scales them with its own image pipeline.
//!   * `set_title` sets the appindicator `XAyatanaLabel` property. The
//!     Ubuntu appindicator extension renders it as a real `St.Label` next
//!     to the icon, in the panel font: crisp, themed, and spaced identically
//!     to every other tray app, for free.
//!
//! The time is deliberately NOT baked into the icon pixels. Drawing glyphs
//! ourselves means a fixed raster size (soft next to hinted shell text) and
//! a wide image that trips the panel's aspect-preserving squeeze (the
//! "indicator-multiload" path), which manufactures transparent side margins
//! that read as oversized padding. Both problems are invisible to the icon
//! plus native-label approach because the shell owns the text.

use std::sync::Mutex;
use std::time::Duration;

use tauri::image::Image;
use tauri::{AppHandle, Manager, Wry};

/// The tray icon id registered in `lib.rs`.
const TRAY_ID: &str = "main-tray";

/// The stopwatch mark: a 48x48 coverage mask generated by
/// `scripts/render_logo.py` from the app icon and stored as raw alpha bytes.
/// Values are alpha 0-255; the flat tint is applied per logging state. The
/// mask is cropped to the mark and fills the slot, so the panel scales it up
/// to match the other tray icons. The chevron and underscore are carved as
/// negative space, so the monochrome mark stays legible on any panel color.
const MARK: &[u8; 48 * 48] = include_bytes!("../icons/tray-mark.bin");

/// The mark as a flat-tinted, straight-RGBA square: the baked alpha mask
/// colored by logging state. Accent while logging, near-white when idle.
/// No text here; the time rides on the native label (`set_title`).
fn render_mark(running: bool) -> (Vec<u8>, u32, u32) {
    let (r, g, b) = if running {
        (221u8, 56, 115) // accent; matches --accent in styles.css
    } else {
        (235u8, 235, 235) // idle; near-white, like a themed panel icon
    };
    let mut rgba = vec![0u8; MARK.len() * 4];
    for (i, &a) in MARK.iter().enumerate() {
        let d = i * 4;
        rgba[d] = r;
        rgba[d + 1] = g;
        rgba[d + 2] = b;
        rgba[d + 3] = a;
    }
    (rgba, 48, 48)
}

/// The day-time readout: `H:MM`, or `H:MM:SS` when `secs` is on.
fn format_total(total: i64, secs: bool) -> String {
    let total = total.max(0);
    let h = total / 3600;
    let m = (total % 3600) / 60;
    let s = total % 60;
    if secs {
        format!("{h}:{m:02}:{s:02}")
    } else {
        format!("{h}:{m:02}")
    }
}

/// The last rendered signature (the running flag and the string). Skip
/// re-encoding when the visible icon would be identical.
static LAST: Mutex<Option<(bool, String)>> = Mutex::new(None);

/// Recomputes the time tracked today (adding the live elapsed time of the
/// running entry) and repaints the tray icon. This is cheap: it reads the
/// timer snapshot and one setting.
pub fn refresh(app: &AppHandle<Wry>) {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    let (running, started_at, description, today_seconds) = {
        let st = app.state::<crate::state::AppState>();
        let t = st.timer.lock().unwrap();
        (
            t.running,
            t.started_at.clone(),
            t.description.clone(),
            t.today_seconds,
        )
    };
    let secs = app
        .state::<crate::state::AppState>()
        .store
        .as_ref()
        .and_then(|s| s.get_setting("tray_show_seconds"))
        .map(|v| v == "true")
        .unwrap_or(false);

    let elapsed = if running {
        started_at
            .and_then(|s| s.parse::<i64>().ok())
            .map(|start| chrono::Utc::now().timestamp() - start)
            .unwrap_or(0)
    } else {
        0
    };
    let total = today_seconds + elapsed.max(0);
    let text = format_total(total, secs);

    // Only re-render when the visible result changed. The ticker fires often.
    {
        let mut last = LAST.lock().unwrap();
        if last
            .as_ref()
            .is_some_and(|(r, t)| *r == running && *t == text)
        {
            return;
        }
        *last = Some((running, text.clone()));
    }

    // Hover tooltip: the running entry's description plus the total. The
    // crate's GTK backend no-ops this on Linux, but it costs nothing and
    // serves the other platforms.
    let tip = if running {
        format!("{}: {}", description.as_deref().unwrap_or("Untitled"), text)
    } else {
        format!("Today: {text}")
    };
    let _ = tray.set_tooltip(Some(&tip));

    // The time as a native label: the appindicator XAyatanaLabel property,
    // drawn by the shell as a real St.Label in the panel font. Crisp text,
    // themed color, and the same icon-to-text spacing every other tray app
    // gets for free. This is how Slack renders its unread badge.
    let _ = tray.set_title(Some(&text));

    let (rgba, w, h) = render_mark(running);
    let _ = tray.set_icon(Some(Image::new(&rgba, w, h)));
}

/// The adaptive repaint loop. It keeps the running time ticking without a
/// server poll:
///   * Running with seconds shown: 1 second.
///   * Running, no seconds: 20 seconds. This catches minute rollovers.
///   * Idle: 60 seconds. This is a cheap safety net. Data changes already
///     repaint through `broadcast`.
pub fn spawn(app: AppHandle<Wry>) {
    tauri::async_runtime::spawn(async move {
        loop {
            let st = app.state::<crate::state::AppState>();
            let running = st.timer.lock().unwrap().running;
            let secs = st
                .store
                .as_ref()
                .and_then(|s| s.get_setting("tray_show_seconds"))
                .map(|v| v == "true")
                .unwrap_or(false);
            let wait = if running && secs {
                1
            } else if running {
                20
            } else {
                60
            };
            tokio::time::sleep(Duration::from_secs(wait)).await;
            refresh(&app);
        }
    });
}

#[cfg(test)]
mod render_tests {
    use super::*;

    // The mark must stay square: a square icon is clamped to the panel's
    // icon slot and never enters the wide-image path that gets squeezed and
    // grows transparent side margins. All text lives in the native label.
    #[test]
    fn mark_is_square_and_tinted() {
        for running in [true, false] {
            let (rgba, w, h) = render_mark(running);
            assert_eq!(w, h, "the mark must be square");
            assert_eq!(rgba.len(), (w * h * 4) as usize);
            let alpha = |x: u32, y: u32| rgba[((y * w + x) * 4 + 3) as usize];
            assert_eq!(alpha(0, 0), 0, "corner must be transparent");
            // The dial body carries ink; the glyph is carved as negative
            // space so the mark reads on any panel color.
            assert!(alpha(8, 28) > 0, "the dial must be drawn");
            assert_eq!(alpha(25, 28), 0, "the chevron must be carved out");
            assert_eq!(alpha(30, 33), 0, "the underscore must be carved out");
            let inked = (0..w * h)
                .filter(|i| rgba[(*i * 4 + 3) as usize] > 0)
                .count();
            assert!(
                inked > 500,
                "the mark must be substantially drawn, got {inked}"
            );
            // Straight RGBA: the tint is stored un-premultiplied, per state.
            let i = (24 * w + 24) as usize * 4;
            if running {
                assert_eq!(&rgba[i..i + 3], &[221, 56, 115]);
            } else {
                assert_eq!(&rgba[i..i + 3], &[235, 235, 235]);
            }
        }
    }
}
